### ISSUE TITLE
Support to view metadata for  online image via url

### ISSUE THREAD

**Issue by pakosaan** [libexif/exif#15]
What the title says.

**Comment by dfandrich** [comment]
Anyone can use exif/libexif to create a service that does this. It's well
outside the scope of the libexif project, though. If you're talking about
adding support for URLs on the command-line, that's also out of scope. exif is
a tool that follows the UNIX philosophy, and you can already do that by
combining it with another tool to get a file from a URL. For example:

  exif <(curl -L https://github.com/libexif/libexif/raw/master/test/testdata/canon_makernote_variant_1.jpg)

**Comment by pakosaan** [comment]
thank you appreciate it
