### ISSUE TITLE
Test failure on PowerPC / RISC-based systems

### ISSUE THREAD

**Issue by hughmcmaster** [libexif/exif#2]
`exif` is mangling one of tags embedded in `no-exif.jpg` incorrectly on PowerPC / RISC-based systems when running the `check-add-tags.sh` test sequence.

The output is `0xa001 Internal error (unknown value 65535)` when the correct value should be `0xa001 Uncalibrated`.

We're seeing this error on a number of Debian build systems (see https://buildd.debian.org/status/package.php?p=exif).

I believe this may be a problem in libexif, but I'm not sure how to debug this.

**Comment by dfandrich** [comment]
We have PPC CI builds that are succeeding, e.g.
https://travis-ci.org/github/libexif/exif/jobs/695316528  How is your failing
environment different?

**Comment by dfandrich** [comment]
Are the failing builds big-endian by chance? We don't have any big-endian CI
builds and it wouldn't entirely surprise me if there were an endianness issue
somewhere.

**Comment by hughmcmaster** [comment]
> Are the failing builds big-endian by chance?

Yes, they are all big endian systems. However, I get the same test failure on a ppc64el Ubuntu VM.

Looking further, this is a problem in libexif. It seems to be caught at line 1314 in `libexif/exif-entry.c`.
`if (list2[i].elem[j].index != v_short) {`

**Comment by msmeissn** [comment]
I also see it on openSUSE ppc64.

**Comment by msmeissn** [comment]
The second fix is the more relevant,... it was passing a unsigned char* pointer instead of using unsigned int* for the p.use_ids passing through.

**Comment by hughmcmaster** [comment]
@msmeissn, I'm still getting the same failure. Admittedly, I only had time to fire up a ppc64el system, but the failure remains.

Can you please look again?

**Comment by msmeissn** [comment]
can you do

make check || cat test/test-suite.log
and attach test-suite.log here?

**Comment by hughmcmaster** [comment]
Sure. Here you go.

[test-suite.log](https://github.com/libexif/exif/files/4885057/test-suite.log)

**Comment by msmeissn** [comment]
Hmm.

It points more to your code piece I have to admit, although I do not see on openSUSE.

I added a fix to libexif, can you see if this helps.

**Comment by dfandrich** [comment]
The FreeBSD tests are failing, but I'm not sure if it's related to this.

**Comment by msmeissn** [comment]
Freebsd seems to have a different issue  I think

**Comment by hughmcmaster** [comment]
@msmeissn All big endian tests are passing on Debian with your two exif commits.

Thanks for working on this bug!

**Comment by msmeissn** [comment]
thanks for checking!
